package io.book.ai.llm;

import java.util.List;

/**
 * Response body received from the Anthropic Messages API.
 *
 * @param content list of content blocks produced by the model
 * @param usage   token consumption statistics for the request
 */
public record AnthropicResponse(List<Content> content, Usage usage) {

    /**
     * A single content block in the model's response.
     *
     * @param type block type — typically {@code "text"}
     * @param text the generated text; present only when {@code type} is {@code "text"}
     */
    public record Content(String type, String text) {}

    /**
     * Token usage reported by the API for billing and quota tracking.
     *
     * @param input_tokens  number of tokens in the request (prompt + system)
     * @param output_tokens number of tokens generated by the model
     */
    public record Usage(int input_tokens, int output_tokens) {}
}
